AGE_CHOICES = [(str(year), str(year)) for year in range(1933, 2007)]

CITIES_CHOICES = [("Jerusalem", "ירושלים"),
          ("Tel Aviv-Yafo", "תל אביב-יפו"),
          ("Haifa", "חיפה"),
          ("Rishon LeZion", "ראשון לציון"),
          ("Petah Tikva", "פתח תקווה"),
          ("Ashdod", "אשדוד"),
          ("Netanya", "נתניה"),
          ("Be'er Sheva", "באר שבע"),
          ("Bnei Brak", "בני ברק"),
          ("Holon", "חולון"),
          ("Ramat Gan", "רמת גן"),
          ("Ashkelon", "אשקלון"),
          ("Rehovot", "רחובות"),
          ("Beit Shemesh", "בית שמש"),
          ("Bat Yam", "בת ים"),
          ("Kfar Saba", "כפר סבא"),
          ("Herzliya", "הרצליה"),
          ("Hadera", "חדרה"),
          ("Modi'in-Maccabim-Re'ut", "מודיעין- מכבים- רעות"),
          ("Lod", "לוד"),
          ("Modi'in Illit", "מודיעין עילית"),
          ("Nazareth", "נצרת"),
          ("Ramla", "רמלה"),
          ("Ra'anana", "רעננה"),
          ("Rahat", "רהט"),
          ("Rosh HaAyin", "ראש העין"),
          ("Hod HaSharon", "הוד השרון"),
          ("Beitar Illit", "ביתר עילית"),
          ("Givatayim", "גבעתיים"),
          ("Kiryat Ata", "קריית אתא"),
          ("Nahariya", "נהריה"),
          ("Kiryat Gat", "קריית גת"),
          ("Umm al-Fahm", "אום אל-פחם"),
          ("Afula", "עפולה"),
          ("Eilat", "אילת"),
          ("Nes Ziona", "נס ציונה"),
          ("Acre", "עכו"),
          ("Yavne", "יבנה"),
          ("El'ad", "אלעד"),
          ("Ramat HaSharon", "רמת השרון"),
          ("Karmiel", "כרמיאל"),
          ("Tiberias", "טבריה"),
          ("Kiryat Motzkin", "קריית מוצקין"),
          ("Tayibe", "טייבה"),
          ("Shefaram", "שפרעם"),
          ("Nof HaGalil", "נוף הגליל"),
          ("Kiryat Bialik", "קריית ביאליק"),
          ("Kiryat Ono", "קריית אונו"),
          ("Kiryat Yam", "קריית ים"),
          ("Netivot", "נתיבות"),
          ("Ma'ale Adumim", "מעלה אדומים"),
          ("Or Yehuda", "אור יהודה"),
          ("Zefat", "צפת"),
          ("Dimona", "דימונה"),
          ("Tamra", "טמרה"),
          ("Ofakim", "אופקים"),
          ("Sakhnin", "סח'נין"),
          ("Baqa al-Gharbiyye", "באקה אל-גרבייה"),
          ("Yehud-Monosson", "יהוד-מונוסון"),
          ("Sderot", "שדרות"),
          ("Be'er Ya'akov", "באר יעקב"),
          ("Giv'at Shmuel", "גבעת שמואל"),
          ("Arad", "ערד"),
          ("Tira", "טירה"),
          ("Arraba", "עראבה"),
          ("Kfar Yona", "כפר יונה"),
          ("Migdal HaEmek", "מגדל העמק"),
          ("Kiryat Malakhi", "קריית מלאכי"),
          ("Kafr Qasim", "כפר קאסם"),
          ("Tirat Carmel", "טירת כרמל"),
          ("Yokneam Illit", "יקנעם עילית"),
          ("Nesher", "נשר"),
          ("Qalansawe", "קלנסווה"),
          ("Kiryat Shmona", "קריית שמונה"),
          ("Ma'alot-Tarshiha", "מעלות- תרשיחא"),
          ("Ariel", "אריאל"),
          ("Or Akiva", "אור עקיבא"),
          ("Beit She'an", "בית שאן")]
