export const HOST_URL = 'http://127.0.0.1:8000/'

export const years = (s, e) => {return [Array.from({ length: e - s + 1 }, (_, index) => s + index)][0]}

export const EDUCATION_LEVEL = [
    ['bachelors_degree', 'תואר ראשון'],
    ['masters_degree', 'תואר שני'],
    ['doctorate', 'דוקטורט'],
    ['teaching_certificate', 'תעודת הוראה'],
    ['diploma', 'לימודי תעודה'],
    ['high_school', 'תיכון'],
];

export const EXPERIENCE_WITH = [
    { "value": "adhd", "label": "קשב וריכוז" },
    { "value": "teaching", "label": "הוראה" },
];

export const CITIES_CHOICES = [
    { "value": "Jerusalem", "label": "ירושלים" },
    { "value": "Tel Aviv-Yafo", "label": "תל אביב-יפו" },
    { "value": "Haifa", "label": "חיפה" },
    { "value": "Rishon LeZion", "label": "ראשון לציון" },
    { "value": "Petah Tikva", "label": "פתח תקווה" },
    { "value": "Ashdod", "label": "אשדוד" },
    { "value": "Netanya", "label": "נתניה" },
    { "value": "Be'er Sheva", "label": "באר שבע" },
    { "value": "Bnei Brak", "label": "בני ברק" },
    { "value": "Holon", "label": "חולון" },
    { "value": "Ramat Gan", "label": "רמת גן" },
    { "value": "Ashkelon", "label": "אשקלון" },
    { "value": "Rehovot", "label": "רחובות" },
    { "value": "Beit Shemesh", "label": "בית שמש" },
    { "value": "Bat Yam", "label": "בת ים" },
    { "value": "Kfar Saba", "label": "כפר סבא" },
    { "value": "Herzliya", "label": "הרצליה" },
    { "value": "Hadera", "label": "חדרה" },
    { "value": "Modi'in-Maccabim-Re'ut", "label": "מודיעין- מכבים- רעות" },
    { "value": "Lod", "label": "לוד" },
    { "value": "Modi'in Illit", "label": "מודיעין עילית" },
    { "value": "Nazareth", "label": "נצרת" },
    { "value": "Ramla", "label": "רמלה" },
    { "value": "Ra'anana", "label": "רעננה" },
    { "value": "Rahat", "label": "רהט" },
    { "value": "Rosh HaAyin", "label": "ראש העין" },
    { "value": "Hod HaSharon", "label": "הוד השרון" },
    { "value": "Beitar Illit", "label": "ביתר עילית" },
    { "value": "Givatayim", "label": "גבעתיים" },
    { "value": "Kiryat Ata", "label": "קריית אתא" },
    { "value": "Nahariya", "label": "נהריה" },
    { "value": "Kiryat Gat", "label": "קריית גת" },
    { "value": "Umm al-Fahm", "label": "אום אל-פחם" },
    { "value": "Afula", "label": "עפולה" },
    { "value": "Eilat", "label": "אילת" },
    { "value": "Nes Ziona", "label": "נס ציונה" },
    { "value": "Acre", "label": "עכו" },
    { "value": "Yavne", "label": "יבנה" },
    { "value": "El'ad", "label": "אלעד" },
    { "value": "Ramat HaSharon", "label": "רמת השרון" },
    { "value": "Karmiel", "label": "כרמיאל" },
    { "value": "Tiberias", "label": "טבריה" },
    { "value": "Kiryat Motzkin", "label": "קריית מוצקין" },
    { "value": "Tayibe", "label": "טייבה" },
    { "value": "Shefaram", "label": "שפרעם" },
    { "value": "Nof HaGalil", "label": "נוף הגליל" },
    { "value": "Kiryat Bialik", "label": "קריית ביאליק" },
    { "value": "Kiryat Ono", "label": "קריית אונו" },
    { "value": "Kiryat Yam", "label": "קריית ים" },
    { "value": "Netivot", "label": "נתיבות" },
    { "value": "Ma'ale Adumim", "label": "מעלה אדומים" },
    { "value": "Or Yehuda", "label": "אור יהודה" },
    { "value": "Zefat", "label": "צפת" },
    { "value": "Dimona", "label": "דימונה" },
    { "value": "Tamra", "label": "טמרה" },
    { "value": "Ofakim", "label": "אופקים" },
    { "value": "Sakhnin", "label": "סח'נין" },
    { "value": "Baqa al-Gharbiyye", "label": "באקה אל-גרבייה" },
    { "value": "Yehud-Monosson", "label": "יהוד-מונוסון" },
    { "value": "Sderot", "label": "שדרות" },
    { "value": "Be'er Ya'akov", "label": "באר יעקב" },
    { "value": "Giv'at Shmuel", "label": "גבעת שמואל" },
    { "value": "Arad", "label": "ערד" },
    { "value": "Tira", "label": "טירה" },
    { "value": "Arraba", "label": "עראבה" },
    { "value": "Kfar Yona", "label": "כפר יונה" },
    { "value": "Migdal HaEmek", "label": "מגדל העמק" },
    { "value": "Kiryat Malakhi", "label": "קריית מלאכי" },
    { "value": "Kafr Qasim", "label": "כפר קאסם" },
    { "value": "Tirat Carmel", "label": "טירת כרמל" },
    { "value": "Yokneam Illit", "label": "יקנעם עילית" },
    { "value": "Nesher", "label": "נשר" },
    { "value": "Qalansawe", "label": "קלנסווה" },
    { "value": "Kiryat Shmona", "label": "קריית שמונה" },
    { "value": "Ma'alot-Tarshiha", "label": "מעלות- תרשיחא" },
    { "value": "Ariel", "label": "אריאל" },
    { "value": "Or Akiva", "label": "אור עקיבא" },
    { "value": "Beit She'an", "label": "בית שאן" }
  ];
  

