# Generated by Django 4.2.3 on 2023-07-18 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextChat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='id',
            field=models.CharField(max_length=13, primary_key=True, serialize=False),
        ),
    ]
